faceproject/faceproject/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings  #for image
from django.conf.urls.static import static #for image
from testapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.show_face_views, name='home'),
    path('insert/', views.insert_face_views),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

faceproject/testapp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class face(models.Model):
    title=models.CharField(max_length=100)
    body=models.TextField()
    img=models.ImageField(upload_to='images')
    publish=models.DateTimeField(default=timezone.now)
    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title        

faceproject/testapp/forms.py
from django import forms
from testapp.models import face
class faceForm(forms.ModelForm):
    class Meta:
        model=face
        fields='__all__'

faceproject/testapp/views.py
from django.shortcuts import render,redirect
from testapp.models import face
from testapp.forms import faceForm
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
# Create your views here.
def show_face_views(request):
    face_details=face.objects.all()
    paginator=Paginator(face_details,2)
    page_number=request.GET.get('page')
    try:
        face_details=paginator.page(page_number)
    except  PageNotAnInteger:
        face_details=paginator.page(1) 
    except EmptyPage:
        face_details=paginator.page(paginator.num_pages)  
    return render(request,'show.html',{'face_details':face_details})

def insert_face_views(request):
    form=faceForm()
    if request.method=='POST':
        form=faceForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'insert.html',{'form':form})

faceproject/templates/base.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/show.css' %}">
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home'%}"><h1>Facedairy </h1></a>
          </li> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          <li class="nav-item active">
            <a class="nav-link" href="/insert"><h3>AddNew Post</h3></a>
          </li> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
          
        </ul>
      </nav>
     {% block body%}
     {% endblock %}
    
     {% block js%}
     {% endblock %}

  </body>
     
</html>

faceproject/templates/insert.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block body%}
<div class="container">
<h1>Write Your Post Here </h1>
<form name='myform'onsubmit='return validate()' method="Post" enctype="multipart/form-data">
  <span id="sp1"></span>
  {{form.as_p}} 
  {% csrf_token%}
  <input type="submit" value="Submit" class="btn btn-lg btn-success">
  <a href="{% url 'home'%}" class="btn btn-lg btn-primary">Back</a>
</form>

</div>
{% endblock %}


{% block js%}
<script>
var title1=document.querySelector('#id_title');
title1.addEventListener('mouseover',function () {
title1.style.backgroundColor='lightblue';
});
 title1.addEventListener('mouseout',function () {
title1.style.color='blue';
title1.style.backgroundColor='lightgreen';
  });

  var body=document.querySelector('#id_body');
  body.addEventListener('mouseover',function () {
    body.style.backgroundColor='lightblue';
    body.style.color='green';
});
body.addEventListener('mouseout',function () {
  body.style.color='blue';
  body.style.backgroundColor='lightgreen';
  });

  

//title is not a integers
function validate() {
  var mytitle=document.getElementById('id_title').value;
  var rgx=/^[0-9]*$/;
  if(rgx.test(mytitle)){
    document.getElementById('sp1').textContent='please enter letters';
    document.getElementById('sp1').style.color='red';
    document.getElementById('id_title').style.color='red';
    return false;
  }
  else{
   // document.getElementById('sp1').textContent='valid';
    //document.getElementById('sp1').style.color='green';
    return true;
  }
  
}
</script>
{% endblock %}

faceproject/templates/pagination.html
<div class="paginator">
    <span>
        {% if page.has_previous%}
        <a href="?page={{page.previous_page_number}}" class="btn btn-lg btn-primary">Previous</a>
        {% endif%}
    </span>
    <span class="current">
        page{{page.number}} of {{page.paginator.num_pages}}
    </span>
    <span>
        {% if page.has_next%}
        <a href="?page={{page.next_page_number}}" class="btn btn-lg btn-primary">Next</a>
        {% endif%}
    </span>


</div>

faceproject/templates/show.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block body%}
{% for f in face_details%}
<div>
<ul>
    <li id="l1" class="c1">
      <b>  Title:</b>&nbsp&nbsp {{f.title}}
    </li>
    <li id="l2">
       <b> Image: </b>&nbsp&nbsp<img src="{{ f.img.url }}" class="img-responsive" style="width:125px; height:150px" />
    </li>
    <li  id="l3" class="c1">
      <b>  About: </b>&nbsp&nbsp <em>{{f.body|linebreaks}}</em>
    </li>
    <li  id="l4">
      <b> Publish on: </b> &nbsp&nbsp{{f.publish}}
    </li>
</ul>
</div>
<hr style='border:5px solid rgb(240, 97, 97) ' width="90%">

{% endfor%}
{% include 'pagination.html' with page=face_details %}

{% endblock %}


{% block js%}
<script>
var title=document.querySelectorAll('.c1')[0];
title.addEventListener('mouseover',function () {
title.style.backgroundColor='lightblue';
});
 title.addEventListener('mouseout',function () {
title.style.color='blue';
title.style.backgroundColor='lightgreen';
  });

  var body=document.querySelectorAll('.c1')[1];
  body.addEventListener('mouseover',function () {
    body.style.backgroundColor='lightblue';
    body.style.color='green';
});
body.addEventListener('mouseout',function () {
  body.style.color='blue';
  body.style.backgroundColor='lightgreen';
  });

</script>
{% endblock %}